weeding_robot:
    # Publish all joint states -----------------------------------
    joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 50

    # Position Controllers ---------------------------------------
    left_wheel_joint_position_controller:
      type: effort_controllers/JointVelocityController
      joint: left_wheel_joint
      pid: {p: 1.0, i: 1.0, d: 0.0}
    # To add more just add them here as the first one

    right_wheel_joint_position_controller:
      type: effort_controllers/JointVelocityController
      joint: right_wheel_joint
      pid: {p: 1.0, i: 1.0, d: 0.0}
