## USB port
port: /dev/ttyACM0


##### Calibration ####
### accelerometer
accel_x_min: -258.5
accel_x_max: 252
accel_y_min: -253
accel_y_max: 258
accel_z_min: -251
accel_z_max: 265

### magnetometer
# standard calibration
magn_x_min: -600.0
magn_x_max: 600.0
magn_y_min: -600.0
magn_y_max: 600.0
magn_z_min: -600.0
magn_z_max: 600.0

# extended calibration
calibration_magn_use_extended: false
magn_ellipsoid_center: [165.858, -485.905, -98.6949]
magn_ellipsoid_transform: [[0.544653, -0.341490, 0.0397472], [-0.341490, 0.701679, -0.119271], [0.0397472, -0.119271, 0.470112]]

# AHRS to robot calibration
imu_yaw_calibration: 0.0

### gyroscope
gyro_average_offset_x: -0.03
gyro_average_offset_y: 0.02
gyro_average_offset_z: -0.015
